# https://taskfile.dev

version: '3'

vars:
  VERSION: v0.0.1

tasks:
  build:
    cmds:
    - bun build ./frontend/src/main --outfile=bundle.js --outdir ./docker/build --target browser
    # - bun vite build ./frontend --outdir ./docker/build --base /assets
    - cp ./frontend/index.html ./docker/build/index.html
    - docker compose -f docker/docker-compose.yml build
  up:
    cmd: docker compose -f docker/docker-compose.yml up -d
  develop:
    cmd: docker compose -f docker/docker-compose.yml up -d --watch
  down:
    cmd: docker compose -f docker/docker-compose.yml down
  logs:
    cmd: docker compose -f docker/docker-compose.yml logs -f
    interactive: true
  resetdb:
    prompt: THIS WILL WIPE THE POSTGRES DATABASE! Continue?
    cmd: docker volume rm bib_postgres
  postgres:
    cmd: docker exec -it postgres psql
    interactive: true
  rebuild:
    cmds:
      - task: down
      - task: build
      - task: up


  default:
    cmds:
      - echo "Version {{.VERSION}}"
    silent: true
